### ISSUE TITLE
"Never" option acts as if delay = 0 or so

### ISSUE THREAD

**Issue by felix91gr** [elfenware/badger#19]
I have set "Eyes" to "Never", however, it reminds me approximately every 60 seconds. Is this happening for everyone else as well?

**Comment by dar5hak** [comment]
Strange. Could you open dconf Editor and check the value for the `eyes` key in `/com/github/elfenware/badger/timers/`?

**Comment by felix91gr** [comment]
Yep! The value is 0 ^^

**Comment by felix91gr** [comment]
It's hard for me to reproduce. I've just upped it to 60 and then reduced it to 0 and now it's behaving correctly it seems (well I haven't tested it for 60 minutes yet, maybe it's not set internally on "Never" but rather on "60"). But there's definitely a path there that treated the value "0" as "0" instead of as "Never".

**Comment by dar5hak** [comment]
What you saw earlier was 0 acting like 1 (minute). If 0 actually acted like 0, you'd be spammed with notifications so badly it would hang your system. 😅

I've seen that during development and made sure we never actually create a `Timeout` with 0 interval.

Coming back to the bug you mentioned, something caused the timer to start with 1 instead of 0. No idea what. If you encounter it again, please do report your findings.

**Comment by felix91gr** [comment]
Yeah, it's now appearing again, but at more than 1 minute apart. It's still on "Never" and the system value is still in 0. No clue what's happening here.

I've also set the Neck reminder to "Never" and this is happening for it as well :_:

**Comment by dar5hak** [comment]
Okay, I reproduced it. For anything that's 0 when Badger starts (usually at login), it stays 0 and works fine. But if you set it to 0 from the UI, for the duration of that session, it spams you. Let me figure out what's causing this.

**Comment by dar5hak** [comment]
Found it! It was because I was double-checking to avoid the aforementioned hang:

https://github.com/elfenware/badger/blob/0e524550ce5ab4375cd12a0e03d391218681f2a3/src/MainGrid.vala#L100-L102

`set_interval` was never called with a `0` argument, and it was therefore failing to disable the timer once you slided it to **Never**.
