### ISSUE TITLE
Add Status Bar Icon

### ISSUE THREAD

**Issue by andreasomaini** [elfenware/badger#21]
# Why

The first time I opened this app, I didn't understand that after closing the window the timers were still going. I think that a status bar icon could be clearer for people to understand that the app is still working even after closing the window.

## Other solution

Alternatively, it is also possible to simply send a notification every time the window is closed saying that the timers are still running.

**Comment by dar5hak** [comment]
elementary OS HIG recommend against using system indicators for background apps (which is why apps like Clipped and Mail don't show it despite running all the time). elementary users _expect_ things to run in the background without being notified about it.

A persistent dock icon makes sense for apps like Torrential or Rush, which have a way to describe their progress in 0 to 100%, but Badger doesn't have that either.
