### ISSUE TITLE
Per timer checkbox

### ISSUE THREAD

**Issue by andreasomaini** [elfenware/badger#22]
# Why

I think a switch for each timer that turns ON/OFF that single timer is much clearer than having to slide all the way to the left

**Comment by dar5hak** [comment]
Good idea. Let's see if more people are interested.

**Comment by felix91gr** [comment]
That would make quite some sense, actually :)

**Comment by dar5hak** [comment]
According to the HIG:

> Don't use switches to select related items as part of a list, instead use a checkbox. Think of switches as acting on independent services and checkboxes as including objects in a list. This is an important distinction to make.

So checkboxes would be the right choice here instead of switches.

At the very least, this would need:

- A third column in the `MainGrid`, at the very left, to house the checkboxes **OR** we could put checkboxes in the same cell as the text
- Logic to make the `Scale` (the slider) insensitive when the corresponding checkbox is unchecked
- A binding between the checkbox and the `active` property of the `Reminder` object

**Comment by andreasomaini** [comment]
That is a nice idea. I will try to implement it myself [here](https://github.com/andreasomaini/badger/tree/per_timer_checkbox)
