### ISSUE TITLE
Publish on Flathub

### ISSUE THREAD

**Issue by pervoj** [elfenware/badger#55]
This is too good app to be simply accessible only from the Elementary AppCenter. It would be great if it was also available from Flathub. If you allow me, I could publish it there and keep it up to date.

**Comment by dar5hak** [comment]
@pervoj Hey, sure. That would be great. Just that I never took the time to know how Flathub publishing workflow goes. Feel free to go ahead, and tag me in any pull request you make to Flathub.

Unfortunately, I won't be able to test it outside elementary OS. But given that it builds against the stable Odin platform, that shouldn't be much of a problem.

**Comment by pervoj** [comment]
Done ([flathub/com.github.elfenware.badger](https://github.com/flathub/com.github.elfenware.badger)), now we just have to wait for it to appear on Flathub.

I could ask them to give you access to the repository.

**Comment by pervoj** [comment]
https://flathub.org/apps/details/com.github.elfenware.badger

**Comment by dar5hak** [comment]
Also, that app description refers to elementary apps and doesn't make much sense any more. I'm gonna clean it up a bit. 😅

**Comment by pervoj** [comment]
> Do you have the access to the repo too?

I was just asking the same question... :)

> Also, that app description refers to elementary apps and doesn't make much sense any more. I'm gonna clean it up a bit.

I don't think that's necessary. The description is very nice.

**Comment by pervoj** [comment]
It would also be good to add a badge to the README.

https://flathub.org/badges

**Comment by dar5hak** [comment]
> The description is very nice.

It was when I wrote it, but those apps don't exist on Odin AppCenter, and Quilter probably never will. Maybe I'll skip the app names and just call out the activities.

I've been thinking about it for a while, but putting it off because of the translation effort it needs.

**Comment by dar5hak** [comment]
> It would also be good to add a badge to the README.

Yeah. If you have time, feel free to make a PR. If not, I'll get around to it in a day or two.

**Comment by dar5hak** [comment]
Okay, so the elementary AppCenter website now lets you download a Flatpak from any OS. So, the version of Badger built on elementary SDK is available to everyone using a Flatpak-compatible distro: https://appcenter.elementary.io/com.github.elfenware.badger/

With that, we can rely on the CSS variables and classes from the elementary stylesheet to be available in the build. This is not the case for the Flathub build, and leaves us with issues like #57.

For this reason, I have tentatively decided to remove Badger from Flathub (no hard feelings @pervoj); I just don't want to do it as a knee-jerk reaction, so will probably think over it for a day.

CC @matfantinel: What are your thoughts on this?

**Comment by matfantinel** [comment]
@dar5hak from a development standpoint it makes a lot more sense to distribute it only on AppCenter now since it will run everywhere.

For the users, I think it's ok for new ones, but for existing ones it kinda sucks to stop receiving updates if they installed from Flathub. I'm not sure what would be the best migration plan in this case - should a last Flathub build have a warning about this somewhere? Like "Thank you for using Badger! To streamline development, Badger will now be distributed only via AppCenter. To continue receiving updates, please install from {link here}"

**Comment by dar5hak** [comment]
Thanks, Matt. I was thinking along similar lines too. But since Badger has been on Flathub for a mere 11 days, I will pull the trigger. Hard decision, but easier to maintain in the long run. (It's even harder for Reminduck users, so I see your point.)

@pervoj I'm so sorry to let your effort go to waste, but I'm really thinking about the future. And elementary opening up AppCenter Flatpaks so quick was an unexpected change. Thanks a lot for your contribution.
