### ISSUE TITLE
I dodged the Badger

### ISSUE THREAD

**Issue by yochananmarqos** [elfenware/badger#58]
I tried this out and thought it wasn't working since there's no way to know it is. Then I checked my notifications and saw I missed two. I was actually away from my computer with the screen locked, but then caught the next one. A passive notification that disappears after a few seconds is never going to get anyone's attention. 

Consider projects like [SafeEyes](https://github.com/safeeyes). Full screen notifications with sound get one's attention. It also includes support for third-party plugins.

Remember, bad habits die hard.

**Comment by dar5hak** [comment]
Thanks for your feedback. Yes, it's true that you miss notifications if you are away from the system, but I haven't yet found a way to reliably detect when a user is away (#42).

And we're deliberately doing passive notifications, because if you are not using your computer, you're probably already not stressing your body anyway, so it's okay to miss a few.

I understand your use case, but grabbing attention while interrupting someone's focus would be unnecessarily intrusive for most people. Sorry for that!

**Comment by subnut** [comment]
> [...] grabbing attention while interrupting someone's focus would be unnecessarily intrusive for most people

True. The only reason I am using badger instead of SafeEyes is the fact that badger limits itself to showing notifications only.
